# Generated by Django 4.1.1 on 2022-10-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=50, unique=True)),
                ('prodQty', models.IntegerField()),
                ('prodPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_ID', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('C', 'Customer'), ('E', 'Employee')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.user')),
                ('age', models.IntegerField()),
            ],
            bases=('registration.user',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.user')),
                ('address', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=13)),
            ],
            bases=('registration.user',),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('salesCount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.product', unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.supplier'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('salesID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('dateOfSale', models.DateField()),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.product')),
                ('cUser_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.customer')),
                ('eUser_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.employee')),
            ],
        ),
    ]
