# Generated by Django 4.1.1 on 2022-10-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesCount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.supplier')),
            ],
        ),
    ]
