# Generated by Django 4.1.1 on 2022-10-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='mobileNumber',
        ),
    ]
