# Generated by Django 4.1.1 on 2022-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_contact_employee_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileNumber',
            field=models.CharField(max_length=13),
        ),
    ]
